# Generated by Django 5.2.16 on 2026-08-19 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_backfill_product_status_from_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('kind', models.CharField(choices=[('store', 'Tienda'), ('warehouse', 'Almacén')], default='warehouse', max_length=16, verbose_name='tipo')),
                ('is_sellable', models.BooleanField(default=False, help_text='De aquí sale lo que se vende (D3) — como mucho una ubicación vendible a la vez, lo valida el serializer, no el modelo.', verbose_name='vendible')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'ubicación',
                'verbose_name_plural': 'ubicaciones',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delta', models.IntegerField(help_text='Positivo o negativo — cuánto varió respecto al valor anterior.', verbose_name='cambio')),
                ('quantity_before', models.PositiveIntegerField(verbose_name='cantidad anterior')),
                ('quantity_after', models.PositiveIntegerField(verbose_name='cantidad posterior')),
                ('reason', models.CharField(max_length=255, verbose_name='motivo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='realizado por')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='stock.location', verbose_name='ubicación')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.variant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'movimiento de stock',
                'verbose_name_plural': 'movimientos de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='cantidad')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='stock.location', verbose_name='ubicación')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='catalog.variant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'nivel de stock',
                'verbose_name_plural': 'niveles de stock',
                'ordering': ['location__position'],
                'constraints': [models.UniqueConstraint(fields=('variant', 'location'), name='stock_stocklevel_variant_location_unique')],
            },
        ),
    ]
