# Generated by Django 5.2.16 on 2026-08-12 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='clave')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'flag de funcionalidad',
                'verbose_name_plural': 'flags de funcionalidad',
                'ordering': ['name'],
            },
        ),
    ]
