# Generated by Django 5.2.16 on 2026-08-12 11:31

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Imagen'), ('video', 'Vídeo')], db_index=True, default='image', max_length=8, verbose_name='tipo')),
                ('file', models.FileField(upload_to='media-library/%Y/%m/', verbose_name='archivo')),
                ('original', models.FileField(blank=True, help_text='Lo que subió el usuario, antes de convertir. Vacío si no hubo conversión.', upload_to='media-library/originals/%Y/%m/', verbose_name='archivo original')),
                ('thumbnail', models.ImageField(blank=True, help_text='Solo en imágenes. La rejilla del panel no puede cargarlas a tamaño real.', upload_to='media-library/thumbs/%Y/%m/', verbose_name='miniatura')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='texto alternativo')),
                ('alt_text_en', models.CharField(blank=True, max_length=200, verbose_name='texto alternativo (EN)')),
                ('mime_type', models.CharField(blank=True, max_length=80, verbose_name='tipo MIME')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='tamaño en bytes')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='ancho')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='alto')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None, verbose_name='etiquetas')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
            ],
            options={
                'verbose_name': 'archivo de medios',
                'verbose_name_plural': 'archivos de medios',
                'ordering': ['-created_at'],
            },
        ),
    ]
