# Generated by Django 5.2.16 on 2026-08-10 06:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='convertido en pedido el')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'carrito',
                'verbose_name_plural': 'carritos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.BigIntegerField(editable=False, unique=True, verbose_name='número de pedido')),
                ('email', models.EmailField(max_length=254, verbose_name='correo de contacto')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='teléfono')),
                ('status', models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('paid', 'Pagado'), ('processing', 'En preparación'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('partially_refunded', 'Reembolsado parcialmente')], db_index=True, default='pending_payment', max_length=24, verbose_name='estado')),
                ('shipping_recipient', models.CharField(max_length=150, verbose_name='destinatario')),
                ('shipping_line1', models.CharField(max_length=255, verbose_name='dirección')),
                ('shipping_line2', models.CharField(blank=True, max_length=255, verbose_name='dirección (línea 2)')),
                ('shipping_postal_code', models.CharField(max_length=10, verbose_name='código postal')),
                ('shipping_city', models.CharField(max_length=120, verbose_name='localidad')),
                ('shipping_province', models.CharField(max_length=120, verbose_name='provincia')),
                ('shipping_country', models.CharField(default='ES', max_length=2, verbose_name='país')),
                ('billing_name', models.CharField(blank=True, max_length=150, verbose_name='razón social / nombre')),
                ('billing_tax_id', models.CharField(blank=True, max_length=20, verbose_name='NIF/CIF')),
                ('billing_address', models.CharField(blank=True, max_length=400, verbose_name='dirección de facturación')),
                ('invoice_requested', models.BooleanField(default=False, verbose_name='factura solicitada')),
                ('invoice_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='factura solicitada el')),
                ('subtotal_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal sin IVA')),
                ('shipping_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='envío sin IVA')),
                ('vat_rate', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='tipo de IVA')),
                ('vat_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA')),
                ('total_gross', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total con IVA')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='moneda')),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='PaymentIntent de Stripe')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pagado el')),
                ('reserved_until', models.DateTimeField(blank=True, null=True, verbose_name='stock reservado hasta')),
                ('stock_committed', models.BooleanField(default=False, help_text='True cuando el pago se confirmó y el stock salió del almacén.', verbose_name='stock descontado')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado el')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregado el')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelado el')),
                ('customer_note', models.TextField(blank=True, verbose_name='nota del cliente')),
                ('staff_note', models.TextField(blank=True, verbose_name='nota interna')),
                ('user', models.ForeignKey(blank=True, help_text='Vacío en compras como invitado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64, verbose_name='SKU')),
                ('product_name', models.CharField(max_length=200, verbose_name='producto')),
                ('color_name', models.CharField(blank=True, max_length=80, verbose_name='color')),
                ('size_code', models.CharField(blank=True, max_length=8, verbose_name='talla')),
                ('unit_price_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario sin IVA')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad')),
                ('line_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total línea sin IVA')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order', verbose_name='pedido')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='catalog.variant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'línea de pedido',
                'verbose_name_plural': 'líneas de pedido',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], db_index=True, default='requested', max_length=16, verbose_name='estado')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('staff_note', models.TextField(blank=True, verbose_name='nota interna')),
                ('refund_amount_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='importe reembolsado con IVA')),
                ('refunded_at', models.DateTimeField(blank=True, help_text='Se rellena a mano tras ejecutar el reembolso en Stripe.', null=True, verbose_name='reembolsado el')),
                ('restock', models.BooleanField(default=True, help_text='Si la prenda llegó en mal estado, desmarcar.', verbose_name='devolver al stock')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'devolución',
                'verbose_name_plural': 'devoluciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='carrito')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.variant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'línea de carrito',
                'verbose_name_plural': 'líneas de carrito',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('cart', 'variant'), name='orders_cartitem_cart_variant_unique')],
            },
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='orders.orderline', verbose_name='línea de pedido')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.return', verbose_name='devolución')),
            ],
            options={
                'verbose_name': 'línea de devolución',
                'verbose_name_plural': 'líneas de devolución',
                'constraints': [models.UniqueConstraint(fields=('return_request', 'order_line'), name='orders_returnline_request_line_unique')],
            },
        ),
    ]
