# Generated by Django 5.2.16 on 2026-08-19 23:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_orders_cart_one_open_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_carrier',
            field=models.CharField(blank=True, max_length=100, verbose_name='transportista'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='código de seguimiento'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='enlace de seguimiento'),
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(verbose_name='nota')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_notes', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='orders.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'nota de pedido',
                'verbose_name_plural': 'notas de pedido',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusChange',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('paid', 'Pagado'), ('processing', 'En preparación'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('partially_refunded', 'Reembolsado parcialmente')], max_length=24, verbose_name='estado anterior')),
                ('to_status', models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('paid', 'Pagado'), ('processing', 'En preparación'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('partially_refunded', 'Reembolsado parcialmente')], max_length=24, verbose_name='estado nuevo')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='motivo')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='realizado por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='orders.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'cambio de estado de pedido',
                'verbose_name_plural': 'cambios de estado de pedido',
                'ordering': ['-created_at'],
            },
        ),
    ]
