# Generated by Django 5.2.16 on 2026-08-10 06:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='nombre (EN)')),
                ('hex_value', models.CharField(blank=True, help_text='Para la muestra en el frontend, p. ej. #C41E3A.', max_length=7, verbose_name='color hexadecimal')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='nombre (EN)')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'familia',
                'verbose_name_plural': 'familias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='talla')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'talla',
                'verbose_name_plural': 'tallas',
                'ordering': ['position', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='nombre (EN)')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category', verbose_name='categoría padre')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('design_code', models.CharField(help_text='Segundo segmento del SKU. Único dentro de la familia.', max_length=16, verbose_name='número de diseño')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='nombre (EN)')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('description_en', models.TextField(blank=True, verbose_name='descripción (EN)')),
                ('composition', models.CharField(blank=True, max_length=255, verbose_name='composición')),
                ('care', models.TextField(blank=True, verbose_name='cuidados')),
                ('kind', models.CharField(choices=[('simple', 'Prenda'), ('bundle', 'Conjunto')], default='simple', max_length=16, verbose_name='tipo')),
                ('sale_mode', models.CharField(choices=[('in_stock', 'Disponible en stock'), ('on_request', 'Solo consulta (sin precio)'), ('made_to_order', 'Bajo encargo')], default='in_stock', max_length=16, verbose_name='modo de venta')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='PVP **sin IVA**. Vacío solo en productos de tipo «solo consulta».', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='precio sin IVA')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Si está relleno, es el precio que se cobra.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='precio rebajado sin IVA')),
                ('is_outlet', models.BooleanField(default=False, verbose_name='en outlet')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de publicación')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='catalog.category', verbose_name='categorías')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.family', verbose_name='familia')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Colorway',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, help_text='Se genera como familia-diseño-color si se deja vacío.', max_length=64, unique=True, verbose_name='SKU')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colorways', to='catalog.color', verbose_name='color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colorways', to='catalog.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'color de producto',
                'verbose_name_plural': 'colores de producto',
                'ordering': ['position', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='catalog/products/', verbose_name='imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='texto alternativo')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('colorway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.colorway', verbose_name='color de producto')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'imagen de producto',
                'verbose_name_plural': 'imágenes de producto',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='unidades en stock')),
                ('reserved', models.PositiveIntegerField(default=0, help_text='Retenidas por checkouts en curso. Las libera el propio checkout.', verbose_name='unidades reservadas')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('colorway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.colorway', verbose_name='color de producto')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.size', verbose_name='talla')),
            ],
            options={
                'verbose_name': 'variante',
                'verbose_name_plural': 'variantes',
                'ordering': ['size__position'],
            },
        ),
        migrations.CreateModel(
            name='StockNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='avisado el')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='catalog.variant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'aviso de reposición',
                'verbose_name_plural': 'avisos de reposición',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BundleComponent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='cantidad')),
                ('bundle', models.ForeignKey(limit_choices_to={'kind': 'bundle'}, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.product', verbose_name='conjunto')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bundles', to='catalog.variant', verbose_name='pieza')),
            ],
            options={
                'verbose_name': 'pieza de conjunto',
                'verbose_name_plural': 'piezas de conjunto',
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('family', 'design_code'), name='catalog_product_family_design_unique'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sale_mode', 'on_request'), ('price__isnull', False), _connector='OR'), name='catalog_product_price_required_unless_on_request'),
        ),
        migrations.AddConstraint(
            model_name='colorway',
            constraint=models.UniqueConstraint(fields=('product', 'color'), name='catalog_colorway_product_color_unique'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('colorway', 'size'), name='catalog_variant_colorway_size_unique'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('stock'))), name='catalog_variant_reserved_lte_stock'),
        ),
        migrations.AddConstraint(
            model_name='stocknotification',
            constraint=models.UniqueConstraint(condition=models.Q(('notified_at__isnull', True)), fields=('variant', 'email'), name='catalog_stocknotification_pending_unique'),
        ),
        migrations.AddConstraint(
            model_name='bundlecomponent',
            constraint=models.UniqueConstraint(fields=('bundle', 'variant'), name='catalog_bundlecomponent_bundle_variant_unique'),
        ),
    ]
