# Generated by Django 5.2.16 on 2026-08-18 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='nombre (EN)')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='fecha de inicio')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='fecha de fin')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'colección',
                'verbose_name_plural': 'colecciones',
                'ordering': ['-position', '-starts_on', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='line',
            field=models.CharField(choices=[('pret_a_porter', 'Prêt-à-porter'), ('atelier', 'Atelier'), ('archive', 'Archivo')], default='pret_a_porter', max_length=16, verbose_name='línea'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('archived', 'Archivado')], default='draft', help_text='Fuente de verdad de la publicación. `is_published` se deriva de este campo.', max_length=16, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='media.mediaasset', verbose_name='archivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Derivado de `status` en save() — no editar a mano, se sobrescribe.', verbose_name='publicado'),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.collection', verbose_name='colección'),
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='nombre (EN)')),
                ('composition', models.CharField(blank=True, max_length=255, verbose_name='composición')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'tejido',
                'verbose_name_plural': 'tejidos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='fabrics',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.fabric', verbose_name='tejidos'),
        ),
    ]
