# Generated by Django 5.2.16 on 2026-09-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_backfill_product_status_from_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_position',
            field=models.PositiveSmallIntegerField(default=0, help_text='Menor primero. Solo se usa si el producto está destacado.', verbose_name='orden en el escaparate'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Aparece en el escaparate de la home.', verbose_name='destacado'),
        ),
    ]
