# Generated by Django 5.2.16 on 2026-09-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_featured_position_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Esperando a publicar'), ('active', 'Activo'), ('archived', 'Archivado')], default='draft', help_text='Fuente de verdad de la publicación. `is_published` se deriva de este campo.', max_length=16, verbose_name='estado'),
        ),
    ]
