# Generated by Django 5.2.16 on 2026-09-09 00:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='catalog_product_price_required_unless_on_request',
        ),
        migrations.AddField(
            model_name='family',
            name='lines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('pret_a_porter', 'Prêt-à-porter'), ('atelier', 'Atelier'), ('archive', 'Archivo')], max_length=16), blank=True, default=list, help_text='Líneas en las que se ofrece. Vacío = en todas.', size=None, verbose_name='líneas'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), ('sale_mode', 'on_request'), ('price__isnull', False), _connector='OR'), name='catalog_product_price_required_when_active'),
        ),
    ]
