# Generated by Django 5.2.16 on 2026-08-10 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_user_accounts_user_email_ci_unique'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepts_marketing',
            field=models.BooleanField(default=False, verbose_name='acepta comunicaciones'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='apellidos'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='teléfono'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=60, verbose_name='etiqueta')),
                ('recipient', models.CharField(max_length=150, verbose_name='destinatario')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='teléfono')),
                ('line1', models.CharField(max_length=255, verbose_name='dirección')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='dirección (línea 2)')),
                ('postal_code', models.CharField(max_length=10, verbose_name='código postal')),
                ('city', models.CharField(max_length=120, verbose_name='localidad')),
                ('province', models.CharField(max_length=120, verbose_name='provincia')),
                ('country', models.CharField(default='ES', max_length=2, verbose_name='país')),
                ('tax_id', models.CharField(blank=True, help_text='Necesario si el cliente pide factura.', max_length=20, verbose_name='NIF/CIF')),
                ('is_default_shipping', models.BooleanField(default=False, verbose_name='envío por defecto')),
                ('is_default_billing', models.BooleanField(default=False, verbose_name='facturación por defecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
                'ordering': ['-is_default_shipping', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='catalog.product', verbose_name='producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'favorito',
                'verbose_name_plural': 'favoritos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='accounts_favorite_user_product_unique')],
            },
        ),
    ]
