# Generated by Django 5.2.16 on 2026-08-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_accepts_marketing_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Confirma que la dirección pertenece a quien se registró. No bloquea el acceso: es una decisión de producto pendiente (ver DECISIONS_PENDING.md).', verbose_name='correo verificado'),
        ),
    ]
