# Generated by Django 5.2.16 on 2026-08-18 22:50

import apps.media.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Imagen'), ('video', 'Vídeo')], max_length=8, verbose_name='tipo')),
                ('file', models.FileField(upload_to=apps.media.models.media_upload_path, verbose_name='archivo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.media.models.thumbnail_upload_path, verbose_name='miniatura')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='nombre original')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='tipo de contenido')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='peso en bytes')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='ancho')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='alto')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='texto alternativo')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
            ],
            options={
                'verbose_name': 'archivo de medios',
                'verbose_name_plural': 'archivos de medios',
                'ordering': ['-created_at'],
            },
        ),
    ]
